name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Stage 1 - Build
        run: echo "stage1 build executed"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Stage 2 - Test
        run: echo "stage2 test executed"

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set Environment Variables
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "COMMIT_ID=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Invoke API and Check Status
        run: |
          RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            -d "{\"pr_number\": \"$PR_NUMBER\", \"commit_id\": \"$COMMIT_ID\"}" \
            "https://api.example.com/api/pr/status")
          
          if [ "$RESPONSE_CODE" -eq 200 ]; then
            echo "API call successful. Stage 3 proceeding."
            echo "stage3 release executed"
          else
            echo "API call failed with status code $RESPONSE_CODE"
            exit 1
          fi
